var struct_z___construct___u_function___a_v_r___pick_up_object___set_both_hands___statics =
[
    [ "VR_PickUpObject_eventSetBothHands_Parms", "struct_z___construct___u_function___a_v_r___pick_up_object___set_both_hands___statics_1_1_v_r___cdd79a0fb2ddd241d5162db7ba258b52.html", "struct_z___construct___u_function___a_v_r___pick_up_object___set_both_hands___statics_1_1_v_r___cdd79a0fb2ddd241d5162db7ba258b52" ]
];