var struct_z___construct___u_function___a_v_r___weapon_base___get_trigger_push_int___statics =
[
    [ "VR_WeaponBase_eventGetTriggerPushInt_Parms", "struct_z___construct___u_function___a_v_r___weapon_base___get_trigger_push_int___statics_1_1_v_rdfecd3eb12b0b96a5167ba8d38fa8e8c.html", "struct_z___construct___u_function___a_v_r___weapon_base___get_trigger_push_int___statics_1_1_v_rdfecd3eb12b0b96a5167ba8d38fa8e8c" ]
];