var struct_z___construct___u_function___a_v_r___bullet___get_caliber___statics =
[
    [ "VR_Bullet_eventGetCaliber_Parms", "struct_z___construct___u_function___a_v_r___bullet___get_caliber___statics_1_1_v_r___bullet__event_get_caliber___parms.html", "struct_z___construct___u_function___a_v_r___bullet___get_caliber___statics_1_1_v_r___bullet__event_get_caliber___parms" ]
];