var struct_z___construct___u_function___a_v_r___weapon_base___get_weapon___statics =
[
    [ "VR_WeaponBase_eventGetWeapon_Parms", "struct_z___construct___u_function___a_v_r___weapon_base___get_weapon___statics_1_1_v_r___weapon_base__event_get_weapon___parms.html", "struct_z___construct___u_function___a_v_r___weapon_base___get_weapon___statics_1_1_v_r___weapon_base__event_get_weapon___parms" ]
];