var struct_z___construct___u_function___a_v_r___game_pad___get_thumbstick_facing_direction___statics =
[
    [ "VR_GamePad_eventGetThumbstickFacingDirection_Parms", "struct_z___construct___u_function___a_v_r___game_pad___get_thumbstick_facing_direction___staticsf1eb4c4c6d5c3c0caac87de1a05d4316.html", "struct_z___construct___u_function___a_v_r___game_pad___get_thumbstick_facing_direction___staticsf1eb4c4c6d5c3c0caac87de1a05d4316" ]
];