var struct_z___construct___u_function___a_v_r___ammo___get_ammo___statics =
[
    [ "VR_Ammo_eventGetAmmo_Parms", "struct_z___construct___u_function___a_v_r___ammo___get_ammo___statics_1_1_v_r___ammo__event_get_ammo___parms.html", "struct_z___construct___u_function___a_v_r___ammo___get_ammo___statics_1_1_v_r___ammo__event_get_ammo___parms" ]
];