var struct_z___construct___u_function___a_v_r___weapon_base___get_just_droped___statics =
[
    [ "VR_WeaponBase_eventGetJustDroped_Parms", "struct_z___construct___u_function___a_v_r___weapon_base___get_just_droped___statics_1_1_v_r___we237a5f010d2d14dbecdd8e0fca52a1c9.html", "struct_z___construct___u_function___a_v_r___weapon_base___get_just_droped___statics_1_1_v_r___we237a5f010d2d14dbecdd8e0fca52a1c9" ]
];