var struct_z___construct___u_function___a_v_r___player_pawn___get_menu_status___statics =
[
    [ "VR_PlayerPawn_eventGetMenuStatus_Parms", "struct_z___construct___u_function___a_v_r___player_pawn___get_menu_status___statics_1_1_v_r___plbd8c49bf2d827ec5326350fddd8e7a96.html", "struct_z___construct___u_function___a_v_r___player_pawn___get_menu_status___statics_1_1_v_r___plbd8c49bf2d827ec5326350fddd8e7a96" ]
];