var struct_z___construct___u_function___a_int___lever___rotatable___get_current_angle___statics =
[
    [ "Int_Lever_Rotatable_eventGetCurrentAngle_Parms", "struct_z___construct___u_function___a_int___lever___rotatable___get_current_angle___statics_1_1_3fe7185627db55211efb54c463dccc3c.html", "struct_z___construct___u_function___a_int___lever___rotatable___get_current_angle___statics_1_1_3fe7185627db55211efb54c463dccc3c" ]
];