var struct_z___construct___u_function___a_v_r___player_pawn___get_health___statics =
[
    [ "VR_PlayerPawn_eventGetHealth_Parms", "struct_z___construct___u_function___a_v_r___player_pawn___get_health___statics_1_1_v_r___player_pawn__event_get_health___parms.html", "struct_z___construct___u_function___a_v_r___player_pawn___get_health___statics_1_1_v_r___player_pawn__event_get_health___parms" ]
];