var struct_z___construct___u_function___a_v_r___player_pawn___heal___statics =
[
    [ "VR_PlayerPawn_eventHeal_Parms", "struct_z___construct___u_function___a_v_r___player_pawn___heal___statics_1_1_v_r___player_pawn__event_heal___parms.html", "struct_z___construct___u_function___a_v_r___player_pawn___heal___statics_1_1_v_r___player_pawn__event_heal___parms" ]
];