var struct_z___construct___u_function___a_v_r___weapon_base___fire___statics =
[
    [ "VR_WeaponBase_eventFire_Parms", "struct_z___construct___u_function___a_v_r___weapon_base___fire___statics_1_1_v_r___weapon_base__event_fire___parms.html", "struct_z___construct___u_function___a_v_r___weapon_base___fire___statics_1_1_v_r___weapon_base__event_fire___parms" ]
];