var struct_z___construct___u_function___a_v_r___player_pawn___enable_camera_fade_on_obj___statics =
[
    [ "VR_PlayerPawn_eventEnableCameraFadeOnObj_Parms", "struct_z___construct___u_function___a_v_r___player_pawn___enable_camera_fade_on_obj___statics_1_dca47ecc26b758ee0b74dace12eb7d13.html", "struct_z___construct___u_function___a_v_r___player_pawn___enable_camera_fade_on_obj___statics_1_dca47ecc26b758ee0b74dace12eb7d13" ]
];