var struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_just_shoot___statics =
[
    [ "VR_WeaponAnimInstance_eventGetJustShoot_Parms", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_just_shoot___statics_1_1_c1e633c2deb04fd2d59c6ee6ce223632.html", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_just_shoot___statics_1_1_c1e633c2deb04fd2d59c6ee6ce223632" ]
];