var struct_z___construct___u_function___a_v_r___motion_controller___get_allow_turn_off_menu___statics =
[
    [ "VR_MotionController_eventGetAllowTurnOffMenu_Parms", "struct_z___construct___u_function___a_v_r___motion_controller___get_allow_turn_off_menu___staticab8451ed1dc14d628d2509995a919d8c.html", "struct_z___construct___u_function___a_v_r___motion_controller___get_allow_turn_off_menu___staticab8451ed1dc14d628d2509995a919d8c" ]
];