var struct_z___construct___u_function___a_int___door___set_one_side___statics_1_1_int___door__event_set_one_side___parms =
[
    [ "flip_side", "struct_z___construct___u_function___a_int___door___set_one_side___statics_1_1_int___door__event_set_one_side___parms.html#ab9d0e185af1d004875cbc2d1acf134af", null ],
    [ "one_side", "struct_z___construct___u_function___a_int___door___set_one_side___statics_1_1_int___door__event_set_one_side___parms.html#ad26422629d7d9422fae1fdb91b4a7b23", null ]
];