var struct_z___construct___u_function___a_v_r___motion_controller___get_hand___statics =
[
    [ "VR_MotionController_eventGetHand_Parms", "struct_z___construct___u_function___a_v_r___motion_controller___get_hand___statics_1_1_v_r___mote1fce73a5d5f1e8f46bb1f220394aba4.html", "struct_z___construct___u_function___a_v_r___motion_controller___get_hand___statics_1_1_v_r___mote1fce73a5d5f1e8f46bb1f220394aba4" ]
];