var struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_lats_bullet_shot___statics =
[
    [ "VR_WeaponAnimInstance_eventGetLatsBulletShot_Parms", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_lats_bullet_shot___staticd8f171c69e0e6ede39db2f4b4371e8fe.html", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_lats_bullet_shot___staticd8f171c69e0e6ede39db2f4b4371e8fe" ]
];