var struct_z___construct___u_function___u_v_r___weapon_anim_instance___set_safer_pressed___statics =
[
    [ "VR_WeaponAnimInstance_eventSetSaferPressed_Parms", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___set_safer_pressed___statics_16bf6ec3cba583673f6bc9be3dbe397ff.html", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___set_safer_pressed___statics_16bf6ec3cba583673f6bc9be3dbe397ff" ]
];