var struct_z___construct___u_function___a_v_r___motion_controller___get_initial_controller_rotation___statics =
[
    [ "VR_MotionController_eventGetInitialControllerRotation_Parms", "struct_z___construct___u_function___a_v_r___motion_controller___get_initial_controller_rotation_7676386ee01e41d981a5b7b87d147d7d.html", "struct_z___construct___u_function___a_v_r___motion_controller___get_initial_controller_rotation_7676386ee01e41d981a5b7b87d147d7d" ]
];