var struct_z___construct___u_function___a_v_r___player_pawn___recive_damage___statics =
[
    [ "VR_PlayerPawn_eventReciveDamage_Parms", "struct_z___construct___u_function___a_v_r___player_pawn___recive_damage___statics_1_1_v_r___playce7fde9b803edb81dbec4750b8b8932b.html", "struct_z___construct___u_function___a_v_r___player_pawn___recive_damage___statics_1_1_v_r___playce7fde9b803edb81dbec4750b8b8932b" ]
];