var struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_safer_pressed___statics =
[
    [ "VR_WeaponAnimInstance_eventGetSaferPressed_Parms", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_safer_pressed___statics_1ddebfe15105a5762b5dbaa79ab59bbb6.html", "struct_z___construct___u_function___u_v_r___weapon_anim_instance___get_safer_pressed___statics_1ddebfe15105a5762b5dbaa79ab59bbb6" ]
];