var struct_z___construct___u_function___a_v_r___player_pawn___on_camera_collision_overlap_begin___statics =
[
    [ "VR_PlayerPawn_eventOnCameraCollisionOverlapBegin_Parms", "struct_z___construct___u_function___a_v_r___player_pawn___on_camera_collision_overlap_begin___st66c414b0cc46d0dd12eb5453adefb112.html", "struct_z___construct___u_function___a_v_r___player_pawn___on_camera_collision_overlap_begin___st66c414b0cc46d0dd12eb5453adefb112" ]
];