var struct_z___construct___u_function___a_int___door___set_angle_limit___statics =
[
    [ "Int_Door_eventSetAngleLimit_Parms", "struct_z___construct___u_function___a_int___door___set_angle_limit___statics_1_1_int___door__event_set_angle_limit___parms.html", "struct_z___construct___u_function___a_int___door___set_angle_limit___statics_1_1_int___door__event_set_angle_limit___parms" ]
];